---
title: "analysis"
output: html_document
date: "2023-08-15"
---

```{r setup, include=FALSE}
library(ggplot2)
library(ggrepel)
library(EMMREML)
library(reshape2)
library(cobs)
library(cowplot)
library(stringr)
library(viridis)

#bioc packages:
library(edgeR)
library(qvalue)

library(parallel)
library(GGally)

library(UpSetR)
library(mashr)

##cibersort
library(e1071)
library(preprocessCore)
library(edgeR)
library(gridExtra)




```

```{r scripts and dirs}

workDir <- gitDir <- "~/Documents/giterdone/"

dataDir <- paste0(workDir,"data/")
figDir <- paste0(workDir,"figures/")
outDir <- paste0(workDir,"output/")

dir.create(dataDir)
dir.create(figDir)
dir.create(outDir)

source(paste0(gitDir,"meerkatPaper/rScripts/gatherData.R"))
source(paste0(gitDir,"meerkatPaper/rScripts/generateResiduals.R"))
source(paste0(gitDir,"meerkatPaper/rScripts/runEmmreml.R"))
source(paste0(gitDir,"meerkatPaper/rScripts/runResponseEmreml.R"))
source(paste0(gitDir,"meerkatPaper/rScripts/perm.fdr.R"))
source(paste0(gitDir,"meerkatPaper/rScripts/compLMMBeta.R"))
source(paste0(gitDir,"meerkatPaper/rScripts/gsea.R"))


```
